const mongoose = require('mongoose');

const preflightSchema = new mongoose.Schema({
    callsign: String,
    cid: String,
    realname: String,
    clienttype: String,
    frequency: String,
    latitude: String,
    longitude: String,
    altitude: String,
    groundspeed: String,
    planned_aircraft: String,
    planned_tascruise: String,
    planned_depairport: String,
    planned_altitude: String,
    planned_destairport: String,
    server: String,
    protrevision: String,
    rating: String,
    transponder: String,
    facilitytype: String,
    visualrange: String,
    planned_revision: String,
    planned_flighttype: String,
    planned_deptime: String,
    planned_actdeptime: String,
    planned_hrsenroute: String,
    planned_minenroute: String,
    planned_hrsfuel: String,
    planned_minfuel: String,
    planned_altairport: String,
    planned_remarks: String,
    planned_route: String,
    planned_depairport_lat: String,
    planned_depairport_lon: String,
    planned_destairport_lat: String,
    planned_destairport_lon: String,
    atis_message: String,
    time_last_atis_received: String,
    time_logon: String,
    heading: String,
    QNH_iHg: String,
    QNH_Mb: String,
  });

mongoose.model('preflight', preflightSchema);